[project]
name = "python-plugin"
version = "0.1.0"
description = "Example Origen plugin"
requires-python = ">=3.7,<3.13"
authors = [{ name = "Origen-SDK" }]
dependencies = ["origen"]

[dependency-groups]
dev = [
    "pytest>=7",
]

[tool.uv.sources]
origen = { path = "../../python/origen" }

[tool.hatch.build.targets.wheel]
packages = ["python_plugin"]

[tool.hatch.build]
artifacts = ["python_plugin/**/*.toml", "python_plugin/*.toml"]

[build-system]
requires = ["hatchling>=1.17.1,<1.18"]
build-backend = "hatchling.build"
