[tool.poetry]
name = "python_plugin"
version = "0.1.0"
description = ""
authors = ["Stephen McGinty <stephen.f.mcginty@gmail.com>"]

[tool.poetry.dependencies]
origen = { path = "/home/stephen/Code/github/o2/python" }
#origen = { path = "/home/stephen/Code/github/o2/python" }
#origen = "2.0.0-pre2"
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
