name = "example"
# Define a default target that will be used by a new workspace
target = ["falcon"]
# Define a default environment that will be used by a new workspace
#environment = "v93k"
# To make your application workspace run in production mode by default
#mode = "production"

# Revision control parameters for the app itself
app_rc = { system = "git", remote = "https://dummy.origen.git" }
app_session_root = "./tmp/pytest"

# Unit tester parameters for the app itself
# By default, Origen apps use Pytest: https://docs.pytest.org/
app_unit_tester = { system = "pytest" }

# Linter
# Package Manager