# Use this to define your application-specific Origen configuration
# Do not delete it even if you don't use it since it is also used by the Origen
# command line interface to determine when it is in an Origen application workspace

# Specify what command should be used to invoke python, if not specified
# Origen will try python, python3, python3.8, etc. until one is found that
# satisfies the minimum Python version requirement
#python_cmd = "mypython"

# If your company has an internal package server enter it here:
#pkg_server = "https://pkgs.company.net:9292"
# or here, if you need to use different urls for push and pull (write and read):
#pkg_server_push = "https://pkgs.company.net:9292"
#pkg_server_pull = "https://pkgs.company.net:9292"

### Users Setup ###
# Various items to customize user data
#
# If any datasets are available, selects which is the default
user__data_lookup_hierarchy = ["test", "backup"]
user__password_cache_option = "none"
# Allows passwords to be stored in the user's session store
#
# User datasets allow for single user to be "registered" in multiple systems
[user__datasets]
[user__datasets.test]
[user__datasets.test2]
[user__datasets.backup]
[user__datasets.dummy_ldap_ds]
category = "ldaps"
data_store = "dummy_ldap" # Corresponds to LDAP name
data_id = "uid"
data_service_user = "dummy_ldap_read_only"
should_validate_password = true
auto_populate = false
[user__datasets.git]
data_store = "git"
auto_populate = false

# When a password is requested for the given reason, will select the appropriate dataset
[user__dataset_motives]
"rc" = "git"
"just because" = "test2"

[user__dataset_mappings]
[user__dataset_mappings.dummy_ldap_ds]
email = "mail"
last_name = "sn"
uid = "uid"
full_name = "cn"

# LDAP configuration
[ldaps]
[ldaps.dummy_ldap]
server = "ldap://ldap.forumsys.com:389"
base = "dc=example,dc=com"
[ldaps.dummy_ldap.auth]
scheme = "simple_bind"
username = "cn=read-only-admin,dc=example,dc=com"
password = "password"

# Service/functional accounts
[default_users]
[default_users.dummy_ldap_read_only]
username = "cn=read-only-admin,dc=example,dc=com"
password = "password"

[mailer]
server = "smtp.origen.org"
port = 25
auth_method = "None"
domain = "origen.org"
user = "dummy_ldap_read_only"
timeout = 120

[[auxillary_commands]]
    path = "../../test_apps_shared_test_helpers/test_apps_shared_test_helpers/aux_cmds/dummy_cmds.toml"

[[auxillary_commands]]
    path = "../../test_apps_shared_test_helpers/test_apps_shared_test_helpers/aux_cmds/empty_aux_ns.toml"
