# Use this to define your application-specific Origen configuration
# Do not delete it even if you don't use it since it is also used by the Origen
# command line interface to determine when it is in an Origen application workspace

# Specify what command should be used to invoke python, if not specified
# Origen will try python, python3, python3.8, etc. until one is found that
# satisfies the minimum Python version requirement
#python_cmd = "mypython"

# If your company has an internal package server enter it here:
#pkg_server = "https://pkgs.company.net:9292"
# or here, if you need to use different urls for push and pull (write and read):
#pkg_server_push = "https://pkgs.company.net:9292"
#pkg_server_pull = "https://pkgs.company.net:9292"

### Users Setup ###
# Various items to customize user data
#
# If any datasets are available, selects which is the default
user__default_dataset = "test"
# Allows passwords to be stored in the user's session store
user__cache_passwords = false
#
# User datasets allow for single user to be "registered" in multiple systems
[user__datasets]
[user__datasets.test]
[user__datasets.test2]
[user__datasets.forumsys]
data_source = "ldap"
data_lookup = "forumsys" # Corresponds to LDAP name
data_id = "uid"
data_service_user = "forumsys_read_only"
try_password = true
auto_populate = false

# When a password is requested for the given reason, will select the appropriate dataset
[user__password_reasons]
"just because" = "test2"

[user__dataset_mappings]
[user__dataset_mappings.forumsys]
email = "mail"
# username = "userPrincipalName"
last_name = "sn"
# display_name = "cn"
uid = "uid"
full_name = "cn"

# LDAP configuration
# Test server:
# https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/
[ldaps]
[ldaps.forumsys]
server = "ldap://ldap.forumsys.com:389"
base = "dc=example,dc=com"
auth = "simple_bind"
service_user = "forumsys_read_only"

# Service/functional accounts
[service_users]
[service_users.forumsys_read_only]
username = "cn=read-only-admin,dc=example,dc=com"
password = "password"
