name = "example"
# This defines the default target that will be used by a new workspace
target = "dut"
# This defines the default environment that will be used by a new workspace
environment = "v93k"
