# Use this to define your application-specific Origen configuration
# Do not delete it even if you don't use it since it is also used by the Origen
# command line interface to determine when it is in an Origen application workspace
