matrix:
  include:
    - language: rust
      before_script:
        - cd rust/origen
      script:
        - cargo build --verbose --all --workspace --bins
        - cargo test
    # - language: python
    #   python: 3.8
    #   before_script:
    #     - cd example
    #       origen setup
    #   script:
    #     - poetry run pytest