matrix:
  include:
    - language: rust
      rust:
        -  1.40.0
      script:
        - cd rust/origen
        - rustup override set nightly
        - cd pyapi
        - cargo build
        - cd ../
        - cargo build --verbose --all --workspace --bins
        - cargo test
    # - language: python
    #   python: 3.8
    #   before_script:
    #     - cd example
    #       origen setup
    #   script:
    #     - poetry run pytest