[package]
name = "cli"
version = "2.0.0-dev.7"
authors = ["Origen-SDK"]
edition = "2021"
rust-version = "1.87"
workspace = ".."

[[bin]]
name = "origen"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.6.6", features = ["string"] }
origen = { path = ".." }
origen_metal = { path = "../../origen_metal" }
pathdiff = "0.1"
online = "0.2"
time = "0.1.42"
semver = "0.9.0"
lazy_static = "1.4.0"
regex = "1"
toml = "0.5"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
indexmap = {version = "2.14.0", features = ["serde"]}
flate2 = "1.0"
tempfile = "3"
toml_edit = "0.21.1"
similar = "2.7.0"
tar = "0.4"
sha2 = "0.9"
base64-url = "1.4.6"
phf = { version = "0.8.0", features = ["macros"] }

[build-dependencies]
walkdir = "2"
built = "0.8.1"
