[tool.poetry]
name = "python_no_app"
version = "0.1.0"
description = ""
authors = ["Origen-SDK"]

[tool.poetry.dependencies]
python = "^3.6"
origen = { path = "../../python/origen", develop = true }
pytest = "^3.0"
