[project]
name = "python-no-app"
version = "0.1.0"
description = "O2 workspace without an application"
requires-python = ">=3.7,<3.13"
dependencies = [
    "origen",
    "origen-metal",
    "python-plugin",
    "python-plugin-the-second",
    "python-plugin-no-cmds",
    "test-apps-shared-test-helpers",
]

[dependency-groups]
dev = [
    "pytest>=7",
]

[tool.uv]
package = false

[tool.uv.sources]
origen = { path = "../../python/origen" }
origen-metal = { path = "../../python/origen_metal" }
python-plugin = { path = "../python_plugin" }
python-plugin-the-second = { path = "../python_plugin_the_second" }
python-plugin-no-cmds = { path = "../python_plugin_no_cmds" }
test-apps-shared-test-helpers = { path = "../test_apps_shared_test_helpers" }

[tool.pytest.ini_options]
addopts = "--ignore=tests/cmd_building/cmd_testers"
