[[extension]]
extend = "app.arg_opt_warmup"
    [[extension.opt]]
        name = "ec_single_opt"
        help = "Single opt from EC"
        takes_value = true
    [[extension.opt]]
        name = "ec_multi_opt"
        help = "Multi opt from EC"
        long = "ec_multi_opt"
        short = "e"
        long_aliases=["ec_multi", "EC"]
        multiple=true
    [[extension.opt]]
        name = "ec_hidden"
        long = "ec_h_opt"
        help = "Hidden opt from EC"
        hidden = true

[[extension]]
extend = "app.nested_app_cmds.nested_l1"
    [[extension.opt]]
        name = "ec_single_opt_shallow"
        help = "Single opt from EC"
        takes_value = true
    [[extension.opt]]
        name = "ec_flag_opt_shallow"
        help = "Flag opt from EC"
        long= "ec_f"

[[extension]]
extend = "app.nested_app_cmds.nested_l1.nested_l2_b.nested_l3_a"
    [[extension.opt]]
        name = "ec_single_opt_deep"
        help = "Single opt from EC"
        long = "ec_opt"
        long_aliases = ["ec_deep"]
        takes_value = true
    [[extension.opt]]
        name = "ec_flag_opt_deep"
        help = "Flag opt from EC"
        long= "ec_df"
        short = "c"
