SubBlock("generic_clk_ctrl",
         "clk_ctrl.base_controller",
         "GenericClkCtrl",
         offset=0xA000_0000)
SubBlock("fast_clk_ctrl",
         "clk_ctrl.enhanced_controller",
         "FastClkCtrl",
         offset=0xA000_1000)
SubBlock("slow_clk_ctrl",
         "clk_ctrl.enhanced_controller",
         "SlowClkCtrl",
         offset=0xA000_2000)
