[package]
name = "origen"
version = "0.1.0"
authors = ["Stephen McGinty <stephen.f.mcginty@gmail.com>"]
edition = "2018"

# Library used by the CLI and the Python interface
[lib]
name = "origen"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

# The Origen command line interface (CLI) executable, i.e. the 'origen' command
[[bin]]
name = "origen"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
lazy_static = "1.4.0"

[dependencies.pyo3]
version = "0.8.2"
features = ["extension-module"]
