[package]
name = "origen"
version = "2.0.0-pre0"
authors = ["Stephen McGinty <stephen.f.mcginty@gmail.com>"]
license = "MIT"
edition = "2018"
#exclude = []
build = "build.rs"

[workspace]
members = ["cli", "meta"]

[lib]

[dependencies]
lazy_static = "1.4.0"
walkdir = "2"
pathdiff = "0.1"
regex = "1"
semver = "0.9.0"
termcolor = "1"
config = "0.9"
serde = {version = "1.0", features = ["derive"]}
path-clean = "0.1.0"
time = "0.1.42"
pyo3 = "^0.8"
indexmap = "1.3.0"
eval = "0.4.3"
num-traits = "0.2.0"
serde-pickle = "0.6"
pest = "2.1"
pest_derive = "2.1"
enum-utils = "0.1.2"
shellexpand = "1.1.1"
chrono = "0.4.11"
whoami = "0.8.1"

# Per this SO thread: https://stackoverflow.com/questions/37296351/trait-for-numeric-functionality-in-rust
# the num crate includes some useful traits to accept float-like and integer-like things without having to manually enumerate them all.
num = "0.2.0"
meta = { path = "./meta" }

[build-dependencies]
built = "0.3"

[dependencies.num-bigint]
version = "0.2"
features = ["serde"]
