[workspace]
members = [
  "src/cli",
#  "src/pyapi",
]

#[package]
#name = "origen"
#version = "2.0.0-pre0"
#authors = ["Stephen McGinty <stephen.f.mcginty@gmail.com>"]
#edition = "2018"
#build = "build.rs"
#
## Library used by the CLI and the Python interface
#[lib]
#name = "_origen"
#path = "src/lib.rs"
#crate-type = ["lib", "cdylib"]
#
## The Origen command line interface (CLI) executable, i.e. the 'origen' command
#[[bin]]
#name = "origen"
#path = "src/bin.rs"
#
## See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
#[dependencies]
#clap = "2.33.0"
#lazy_static = "1.4.0"
#semver = "0.9.0"
#built = "0.3"
#
#[build-dependencies]
#built = "0.3"
#
#[dependencies.pyo3]
#version = "0.8.2"
#features = ["extension-module"]
