name = "python_plugin"
# Define a default target/environment that will be used by a new workspace
#target = ["dut/falcon", "tester/v93k"]
# To make your application workspace run in production mode by default
#mode = "production"