name: 'Build Origen CLI'
description: 'Installs Rust, builds the Origen CLI and makes it available in the PATH'
inputs:
  rust-version: 
    default: 'nightly'
  release:
    description: "Build a release version of the CLI"
    default: false
  target:
    description: "The Rust build target"
    default: ""

runs:
  using: "composite"
  steps: 
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ inputs.rust-version }}
          override: true
          #components: rustfmt, clippy
    - name: Build Origen CLI (Debug)
      if: ${{ !inputs.release }}
      working-directory: rust/origen/cli
      run: |
        cargo build --bins
        echo "${{ github.workspace }}/rust/origen/target/{{inputs.target}}/debug" >> $GITHUB_PATH
    - name: Build Origen CLI (Release)
      if: ${{ inputs.release }}
      working-directory: rust/origen/cli
      run: |
        cargo build --bins --release
        echo "${{ github.workspace }}/rust/origen/target/{{inputs.target}}/release" >> $GITHUB_PATH

