[project]
name = "example"
version = "1.2.3"
description = "O2 regression test application"
requires-python = ">=3.7,<3.13"
authors = [{ name = "Origen-SDK" }]
dependencies = [
    "origen",
    "origen-metal",
    "python-plugin",
    "test-apps-shared-test-helpers",
    "python-plugin-no-cmds",
]

[dependency-groups]
dev = [
    "pytest>=7",
]

[tool.uv.sources]
origen = { path = "../../python/origen" }
origen-metal = { path = "../../python/origen_metal" }
python-plugin = { path = "../python_plugin" }
test-apps-shared-test-helpers = { path = "../test_apps_shared_test_helpers" }
python-plugin-no-cmds = { path = "../python_plugin_no_cmds" }

[tool.hatch.build.targets.wheel]
packages = ["example"]

[tool.hatch.build]
artifacts = ["example/**/*.toml", "example/*.toml"]

[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = [
    "online: marks tests as requiring an internet connection",
    "ldap: marks tests requiring/using an external LDAP",
]

[build-system]
requires = ["hatchling>=1.17.1,<1.18"]
build-backend = "hatchling.build"
