[project]
name = "python-plugin-no-cmds"
version = "0.1.0"
description = "Example Origen plugin without commands"
requires-python = ">=3.7,<3.13"
authors = [{ name = "Origen-SDK" }]
dependencies = ["origen", "origen-metal"]

[dependency-groups]
dev = [
    "pytest>=7",
]

[tool.uv.sources]
origen = { path = "../../python/origen" }
origen-metal = { path = "../../python/origen_metal" }

[tool.hatch.build.targets.wheel]
packages = ["python_plugin_no_cmds"]

[tool.hatch.build]
artifacts = ["python_plugin_no_cmds/**/*.toml", "python_plugin_no_cmds/*.toml"]

[build-system]
requires = ["hatchling>=1.17.1,<1.18"]
build-backend = "hatchling.build"
