[project]
name = "python-plugin-the-second"
version = "0.1.0"
description = "Second example Origen plugin"
requires-python = ">=3.7,<3.13"
authors = [{ name = "Origen-SDK" }]
dependencies = ["origen", "origen-metal"]

[dependency-groups]
dev = [
    "pytest>=7",
]

[tool.uv.sources]
origen = { path = "../../python/origen" }
origen-metal = { path = "../../python/origen_metal" }

[tool.hatch.build.targets.wheel]
packages = ["python_plugin_the_second"]

[tool.hatch.build]
artifacts = ["python_plugin_the_second/**/*.toml", "python_plugin_the_second/*.toml"]

[build-system]
requires = ["hatchling>=1.17.1,<1.18"]
build-backend = "hatchling.build"
