name: Publish Packages
on: workflow_dispatch
env:
  om_ver_file: om_version
  origen_ver_file: origen_version
jobs:
  build_manylinux:
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS_FOR_RELEASE) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/pypa/manylinux2014_x86_64
          options: --user root
          run: |
            echo "========================================"
            echo "=====         Install Rust         ====="
            echo "========================================"
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
            echo "========================================"
            echo "=====       Set Rust Version       ====="
            echo "========================================"
            rustup install ${{ fromJSON(vars.RUST_VERSION) }}
            rustup default ${{ fromJSON(vars.RUST_VERSION) }}
            echo "========================================"
            echo "=====      Check Rust Version      ====="
            echo "========================================"
            rustc --version
            cargo --version
            echo "========================================"
            echo "=====    Install Newer OpenSSL     ====="
            echo "========================================"
            curl -O -L https://www.openssl.org/source/openssl-1.1.1w.tar.gz
            ls -al openssl-1.1.1w.tar.gz
            tar zxf openssl-1.1.1w.tar.gz
            cd openssl-1.1.1w
            ./config
            make
            make install
            echo "========================================"
            echo "=====        Install libffi        ====="
            echo "========================================"
            yum install libffi-devel -y
            ldconfig
            echo "========================================"
            echo "=====        Install libffi        ====="
            echo "========================================"
            yum install perl-IPC-Cmd -y
            echo "========================================"
            echo "=====        Install Python        ====="
            echo "========================================"
            ls $ROOT_DIR/openssl-1.1.1w
            curl -O https://www.python.org/ftp/python/${{ matrix.python-version }}/Python-${{ matrix.python-version }}.tgz
            tar zxf Python-${{ matrix.python-version }}.tgz
            cd Python-${{ matrix.python-version }}
            ./configure --with-openssl=$ROOT_DIR/openssl-1.1.1w --prefix=/root/python --enable-optimizations --enable-shared
            make altinstall

