name: Publish Packages
on: workflow_dispatch
env:
  om_ver_file: om_version
  origen_ver_file: origen_version
jobs:
  build_manylinux:
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS_FOR_RELEASE) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
