name: Publish Packages
on: workflow_dispatch
env:
  om_ver_file: om_version
  origen_ver_file: origen_version
jobs:
  build_manylinux:
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS_FOR_RELEASE) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/pypa/manylinux2014_x86_64
          options: --user root
          run: |
            echo "=====Install Rust====="
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
            echo "=====Set Rust Version====="
            rustup install ${{ fromJSON(vars.RUST_VERSION) }}
            rustup default ${{ fromJSON(vars.RUST_VERSION) }}
            echo "=====Check Rust Version====="
            rustc --version
            cargo --version
            echo "=====Install Newer OpenSSL====="
            curl -O -L https://www.openssl.org/source/openssl-1.1.1w.tar.gz
            ls -al openssl-1.1.1w.tar.gz
            tar zxf openssl-1.1.1w.tar.gz
            cd openssl-1.1.1w
            ./config
            make
            make install
