name: Regression Tests
on: [push]
jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build_cli@v1
      - run: origen -v
        #- name: Build Origen CLI
        #- working-directory: rust/origen/cli
        #- run: cargo build --bins
