name: Regression Tests
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: "nightly-2020-11-01"
            override: true
            #components: rustfmt, clippy
            
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
            
      - name: Build Origen CLI
        working-directory: rust/origen/cli
        run: cargo build --bins
          
      - name: Add Origen to PATH (Linux)
        if: matrix.os == 'ubuntu-latest'
        run : echo "${{ github.workspace }}/rust/origen/target/debug" >> $GITHUB_PATH

      - name: Add Origen to PATH (Windows)
        if: matrix.os == 'windows-latest'
        run : echo '${{ github.workspace }}\rust\origen\target\debug' >> $GITHUB_PATH
 
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Display Origen CLI Version
        run: origen -v

      - name: Run Rust Tests
        if: matrix.python-version == 3.8
        working-directory: rust/origen
        run: cargo test --workspace

      - name: Build PyAPI
        run: origen build

      - name: Setup App Env
        working-directory: test_apps/python_app
        run: origen env setup

      - name: Display Origen App Version
        working-directory: test_apps/python_app
        run: origen -v

      - name: Run Python Unit Tests
        working-directory: test_apps/python_app
        run: origen exec pytest -vv

      - name: Run Diff Tests
        working-directory: test_apps/python_app
        run: origen examples
